# Generated by Django 3.2.16 on 2025-11-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_auto_20251129_1950'),
        ('account', '0003_auto_20251129_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hiring_categories',
            field=models.ManyToManyField(blank=True, help_text='Categories of workers you typically hire', to='jobapp.Category'),
        ),
    ]
