# Generated by Django 3.2.16 on 2025-12-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_hiring_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief professional bio or about you', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(blank=True, help_text='Upload your CV/Resume (PDF, DOC, DOCX)', null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='City/Region where you are located', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_job_title',
            field=models.CharField(blank=True, help_text='e.g., Software Engineer, Data Analyst', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated list of skills (e.g., Python, Django, JavaScript)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='years_of_experience',
            field=models.IntegerField(blank=True, help_text='Years of professional experience', null=True),
        ),
    ]
