# Generated by Django 3.2.16 on 2025-12-08 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_outgoingemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='Kenyan National ID')),
                ('service_type', models.CharField(choices=[('Housemaid', 'Housemaid'), ('Gatekeeper / Security', 'Gatekeeper / Security'), ('Saloonist / Hairdresser', 'Saloonist / Hairdresser'), ('Barber', 'Barber'), ('Gardener', 'Gardener'), ('Driver', 'Driver'), ('Other', 'Other')], max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DomesticJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('service_category', models.CharField(choices=[('Housemaid', 'Housemaid'), ('Gatekeeper / Security', 'Gatekeeper / Security'), ('Saloonist / Hairdresser', 'Saloonist / Hairdresser'), ('Barber', 'Barber'), ('Gardener', 'Gardener'), ('Driver', 'Driver'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
