# Generated by Django 3.2.16 on 2025-12-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domesticworker',
            name='phone_number',
        ),
    ]
