# Generated by Django 3.2.16 on 2025-11-29 16:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_auto_20251129_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('EN', 'Entry Level'), ('JR', 'Junior'), ('MD', 'Mid-Level'), ('SR', 'Senior'), ('DR', 'Director'), ('EX', 'Executive')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_arrangement',
            field=models.CharField(blank=True, choices=[('ON', 'On-site'), ('RM', 'Remote'), ('HB', 'Hybrid')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FT', 'Full time'), ('PT', 'Part time'), ('IN', 'Internship')], max_length=2),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
